services:
  db:
    container_name: trigger-db-instance
    image: mongo:7.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    networks:
      - trigger
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"

  server:
    container_name: trigger-server-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/server.Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - auth
      - user
      - session
      - sync
      - settings
      - action
      - gmail
      - github
      - spotify
      - twitch
      - discord
      - bitbucket
      - timer
    networks:
      - trigger
    environment:
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GMAIL_SERVICE_BASE_URL: ${GMAIL_SERVICE_BASE_URL}
      GITHUB_SERVICE_BASE_URL: ${GITHUB_SERVICE_BASE_URL}
      BITBUCKET_SERVICE_BASE_URL: ${BITBUCKET_SERVICE_BASE_URL}
      SPOTIFY_SERVICE_BASE_URL: ${SPOTIFY_SERVICE_BASE_URL}
      TWITCH_SERVICE_BASE_URL: ${TWITCH_SERVICE_BASE_URL}
      TIMER_SERVICE_BASE_URL: ${TIMER_SERVICE_BASE_URL}

  auth:
    container_name: trigger-auth-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/auth.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}
      WEB_BASE_URL: ${WEB_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TOKEN_SECRET: ${TOKEN_SECRET}
      AUTH_KEY: ${AUTH_KEY}
      AUTH_MAX_AGES: ${AUTH_MAX_AGES}
      AUTH_IS_PROD: ${AUTH_IS_PROD}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      GITHUB_KEY: ${GITHUB_AUTH_KEY}
      GITHUB_SECRET: ${GITHUB_AUTH_SECRET}
      DISCORD_KEY: ${DISCORD_KEY}
      DISCORD_SECRET: ${DISCORD_SECRET}
      SPOTIFY_KEY: ${SPOTIFY_KEY}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      BITBUCKET_KEY: ${BITBUCKET_AUTH_KEY}
      BITBUCKET_SECRET: ${BITBUCKET_AUTH_SECRET}
  
      AUTH_PORT: ${AUTH_PORT}
      WEB_PORT: ${WEB_PORT}
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"

  user:
    container_name: trigger-user-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/user.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      USER_PORT: ${USER_PORT}
    ports:
      - "${USER_PORT}:${USER_PORT}"

  session:
    container_name: trigger-session-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/session.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SESSION_PORT: ${SESSION_PORT}
    ports:
      - "${SESSION_PORT}:${SESSION_PORT}"

  sync:
    container_name: trigger-sync-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/sync.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}
      WEB_BASE_URL: ${WEB_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      GITHUB_KEY: ${GITHUB_SYNC_KEY}
      GITHUB_SECRET: ${GITHUB_SYNC_SECRET}
      BITBUCKET_KEY: ${BITBUCKET_SYNC_KEY}
      BITBUCKET_SECRET: ${BITBUCKET_SYNC_SECRET}
      DISCORD_KEY: ${DISCORD_KEY}
      DISCORD_SECRET: ${DISCORD_SECRET}
      SPOTIFY_KEY: ${SPOTIFY_KEY}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TOKEN_SECRET: ${TOKEN_SECRET}
      AUTH_KEY: ${AUTH_KEY}
      AUTH_MAX_AGES: ${AUTH_MAX_AGES}
      AUTH_IS_PROD: ${AUTH_IS_PROD}

      AUTH_PORT: ${AUTH_PORT}
      SYNC_PORT: ${SYNC_PORT}
      WEB_PORT: ${WEB_PORT}

      BOT_TOKEN: ${BOT_TOKEN}
      USER_PORT: ${USER_PORT}
    ports:
      - "${SYNC_PORT}:${SYNC_PORT}"

  settings:
    container_name: trigger-settings-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/settings.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      SETTINGS_PORT: ${SETTINGS_PORT}
    ports:
      - "${SETTINGS_PORT}:${SETTINGS_PORT}"

  action:
    container_name: trigger-action-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/action.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GMAIL_SERVICE_BASE_URL: ${GMAIL_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}
      GITHUB_SERVICE_BASE_URL: ${GITHUB_SERVICE_BASE_URL}
      SPOTIFY_SERVICE_BASE_URL: ${SPOTIFY_SERVICE_BASE_URL}
      TWITCH_SERVICE_BASE_URL: ${TWITCH_SERVICE_BASE_URL}
      TIMER_SERVICE_BASE_URL: ${TIMER_SERVICE_BASE_URL}
      DISCORD_SERVICE_BASE_URL: ${DISCORD_SERVICE_BASE_URL}
      BITBUCKET_SERVICE_BASE_URL: ${BITBUCKET_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      ACTION_PORT: ${ACTION_PORT}
    ports:
      - "${ACTION_PORT}:${ACTION_PORT}"

  gmail:
    container_name: trigger-gmail-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/gmail.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GMAIL_SERVICE_BASE_URL: ${GMAIL_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      SETTINGS_SERVICE_BASE_URL: ${SETTINGS_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

      AUTH_PORT: ${AUTH_PORT}
      GMAIL_PORT: ${GMAIL_PORT}
    ports:
      - "${GMAIL_PORT}:${GMAIL_PORT}"

  github:
    container_name: trigger-github-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/github.Dockerfile
    networks:
      - trigger
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      GITHUB_SERVICE_BASE_URL: ${GITHUB_SERVICE_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}

      GITHUB_PORT: ${GITHUB_PORT}
      AUTH_PORT: ${AUTH_PORT}
      GITHUB_KEY: ${GITHUB_SYNC_KEY}
      GITHUB_SECRET: ${GITHUB_SYNC_SECRET}
    ports:
      - "${GITHUB_PORT}:${GITHUB_PORT}"

  bitbucket:
    container_name: trigger-bitbucket-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/bitbucket.Dockerfile
    networks:
      - trigger
    environment:
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}

      BITBUCKET_PORT: ${BITBUCKET_PORT}
      AUTH_PORT: ${AUTH_PORT}
      BITBUCKET_KEY: ${BITBUCKET_SYNC_KEY}
      BITBUCKET_SECRET: ${BITBUCKET_SYNC_SECRET}
    ports:
      - "${BITBUCKET_PORT}:${BITBUCKET_PORT}"

  discord:
    container_name: trigger-discord-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/discord.Dockerfile
    networks:
      - trigger

    environment:
      DISCORD_PORT: ${DISCORD_PORT}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      AUTH_PORT: ${AUTH_PORT}
      DISCORD_KEY: ${DISCORD_KEY}
      DISCORD_SECRET: ${DISCORD_SECRET}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      BOT_TOKEN: ${BOT_TOKEN}
      DISCORD_SERVICE_BASE_URL: ${DISCORD_SERVICE_BASE_URL}

    ports:
      - "${DISCORD_PORT}:${DISCORD_PORT}"

  spotify:
    container_name: trigger-spotify-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/spotify.Dockerfile
    networks:
      - trigger
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST}
      MONGO_DB: ${MONGO_DB}

      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      SPOTIFY_SERVICE_BASE_URL: ${SPOTIFY_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      AUTH_PORT: ${AUTH_PORT}
      SPOTIFY_PORT: ${SPOTIFY_PORT}
      SPOTIFY_KEY: ${SPOTIFY_KEY}
      SPOTIFY_SECRET: ${SPOTIFY_SECRET}
    ports:
      - "${SPOTIFY_PORT}:${SPOTIFY_PORT}"

  twitch:
    container_name: trigger-twitch-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/twitch.Dockerfile
    networks:
      - trigger
    environment:
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      SYNC_SERVICE_BASE_URL: ${SYNC_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}
      TWITCH_SERVICE_BASE_URL: ${TWITCH_SERVICE_BASE_URL}
      SERVER_BASE_URL: ${SERVER_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}

      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      TWITCH_CLIENT_SECRET: ${TWITCH_CLIENT_SECRET}
      AUTH_PORT: ${AUTH_PORT}
      TWITCH_PORT: ${TWITCH_PORT}
    ports:
      - "${TWITCH_PORT}:${TWITCH_PORT}"

  timer:
    container_name: trigger-timer-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/backend/timer.Dockerfile
    networks:
      - trigger
    environment:
      ACTION_SERVICE_BASE_URL: ${ACTION_SERVICE_BASE_URL}
      AUTH_SERVICE_BASE_URL: ${AUTH_SERVICE_BASE_URL}
      SESSION_SERVICE_BASE_URL: ${SESSION_SERVICE_BASE_URL}
      TIMER_SERVICE_BASE_URL: ${TIMER_SERVICE_BASE_URL}
      USER_SERVICE_BASE_URL: ${USER_SERVICE_BASE_URL}

      ADMIN_TOKEN: ${ADMIN_TOKEN}
      TIMER_PORT: ${TIMER_PORT}
    ports:
      - "${TIMER_PORT}:${TIMER_PORT}"

  client_mobile:
    container_name: trigger-mobile-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/frontend/mobile.Dockerfile
    networks:
      - trigger
    volumes:
      - shared_volume:/shared
    environment:
      NGROK: ${NGROK}

  client_web:
    container_name: trigger-web-instance
    build:
      context: ..
      dockerfile: ./deploy/dockerfiles/frontend/web.Dockerfile
    networks:
      - trigger
    depends_on:
      - client_mobile
      - server
    environment:
      WEB_PORT: ${WEB_PORT}
    ports:
      - "8081:${WEB_PORT}"
    volumes:
      - shared_volume:/shared

volumes:
  mongo_data:
    driver: local
  shared_volume:

networks:
  trigger:
    driver: bridge
