import type { Metadata } from "next";
import "./globals.css";

import { Navbar } from "@/components/ui/navbar";
import { Provider } from "@/lib/providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Trigger",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen bg-gray-200 dark:bg-zinc-900">
        <Navbar />
        <Provider>{children}</Provider>
        <Toaster />
      </body>
    </html>
  );
}
